### ISSUE TITLE
ForceLoaded Chunk Support

### ISSUE THREAD

**Issue by null511** [QuiltServerTools/TickTools#13]
On my SMP server using TickTools, I built an iron farm and tried to enable force-load on the chunk. However TickTools doesn't seem to recognize this, and unloads the chunk when no players are nearby. For now I've had to remove TT, but I hope to see this fixed soon so I can add it back to my server.

**Comment by Genau6502** [comment]
Forceload has been implemented in dev branch, and ticking does not occur in some chunks when no-tick is enabled
